### ISSUE TITLE
The error when training the graph_retriever in the HotpotQA

### ISSUE THREAD

**Issue by Frankszc** [AkariAsai/learning_to_retrieve_reasoning_paths#15] opened 2020-04-21 13:12 UTC
Thanks for your great work!
When I run the run_graph_retriever.py ( in the graph_retriever folder) to train the graph-based recurrent retriever model in the train dataset ( the files in the hotpotqa_new_selector_train_data_db_2017_10_12_fix.zip ) of HotpotQA, there is an error like it.
-----------------------------------
Traceback (most recent call last):
  File "run_graph_retriever.py", line 546, in <module>
    main()
  File "run_graph_retriever.py", line 264, in main
    train_examples = processor.get_train_examples(graph_retriever_config)
  File "/DATA/sunzhanchen/learning_to_retrieve_reasoning_paths-master/graph_retriever/utils.py", line 200, in get_train_examples
    examples += self._create_examples(file_name, graph_retriever_config, "train")
  File "/DATA/sunzhanchen/learning_to_retrieve_reasoning_paths-master/graph_retriever/utils.py", line 429, in _create_examples
    assert t in context
AssertionError
-----------------------------------
Is there any question about the train dataset or any other question?
Thanks you again!

**Comment by AkariAsai** [comment] 2020-04-27 00:34
Hi, thank you for posting the issue! :) 
Would you tell us which command did you run when you face this issue? We'd like to reproduce this error in our environment to fix it, as we haven't seen in our environment.  
The error might come from [this assertion error](https://github.com/AkariAsai/learning_to_retrieve_reasoning_paths/blob/8bc397afae9d1e4363609a7bc171fe450afa502b/graph_retriever/utils.py#L427).

**Comment by Frankszc** [comment] 2020-04-29 06:42
> Hi, thank you for posting the issue! :)
> Would you tell us which command did you run when you face this issue? We'd like to reproduce this error in our environment to fix it, as we haven't seen in our environment.
> The error might come from this assertion error.

Thanks for your reply, and the command I used is
---------------------------------
python run_graph_retriever.py \
--task hotpot_open \
--bert_model bert-base-uncased --do_lower_case \
--train_file_path ./data/hotpotqa_new_selector_train_data_db_2017_10_12_fix/db=wiki_hotpotqa.db_hotpotqa_new_test_tfidf_k=50.pruning_l=100_tag_me=True.prune_after_agg=False.prune_in_article=False_use_link=True_start= \
--output_dir ./train_model/retriever/ \
--max_para_num 50 \
--tfidf_limit 40 \
--neg_chunk 8 --train_batch_size 4 --gradient_accumulation_steps 1 \
--learning_rate 3e-5 --num_train_epochs 3 \
--use_redundant \
--max_select_num 4 \
---------------------------------
 I want to train the graph-based recurrent retriever model in the HotpotQA train dataset.

**Comment by AkariAsai** [comment] 2020-09-14 08:47
Sorry for my late response. It seems that the path to train data may not be correct `./data/hotpotqa_new_selector_train_data_db_2017_10_12_fix/db=wiki_hotpotqa.db_hotpotqa_new_test_tfidf_k=50.pruning_l=100_tag_me=True.prune_after_agg=False.prune_in_article=False_use_link=True_start=` but I'm not sure if it's just copying error. I have tried to run training on HotpotQA using our data and codes and I couldn't reproduce the error... 

Although I'm not sure if it's the case, I got similar kinds of errors when I was running our model on our own internal data. At that time, I have mistakenly fed inputs with empty context as a TF-IDF retriever failed to return any paragraphs due to some special characters. I'm not sure if it's related to your case or not.

**Comment by sysu-zjw** [comment] 2020-12-01 04:44
Hi, I encounter the same error. However, it works after I change `--tfidf_limit 40` to `--tfidf_limit 60`. I wonder why this happens as `--tfidf_limit` seems only to control the number of negative samples?

**Comment by AkariAsai** [comment] 2021-01-07 02:46
Thanks, @sysu-zjw for the update! We've tested the code mostly with python 3.6, so the issue you pointed out might have caused the problem. @Frankszc, I close this issue now but please feel free to re-open.

**Closed by AkariAsai** 2021-01-07 02:46 UTC
Labels: bug, question
